### ISSUE TITLE
Should the dealer even play if he is the last player standing?

### ISSUE THREAD

**Issue by Kbam7** [MrGarrson47/BlackJackV2#2]
Just seems strange that the dealer still has to compete against the house even thought all the players have already lost. We should totally look into the rules of blackjack to see how it should work or just make up our own 😋

**Comment by Stephen-Jason** [comment]
I found this today https://wizardofvegas.com/forum/gambling/blackjack/21448-does-the-dealer-finish-drawing-cards-if-the-player-bust/ , people answered that no, the dealer doesn't play if there are no active players, lets go with this, it does make more sense than the dealer just drawing cards when the outcome(he busts or doesn't) won't affect anything.
